
---

- hosts: all
  become: true
  tasks:
  
  - name: install apache and php package ubuntu
    package: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansbile_distribution == "Ubuntu"
      
  - name: install apache and php package centos
    dnf: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansbile_distribution == "CentOS"
