
---

- hosts: all
  become: true
  pre_tasks:
   - name: install updates (centos)
     dnf:
      update_only: yes
      update_cache: yes
     when: ansible_distribution == "CentOS"
   - name: install updates (ubuntu)
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

- hosts: Web_Server
  become: true
  tasks:
   - name: install apache and php package ubuntu
     apt: 
       name: 
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
   - name: install apache and php package centos
     dnf: 
       name: 
         - httpd
         - php
       state: latest
     when: ansible_distribution == "CentOS"
    
- hosts: DB_Server
  become: true
  tasks:
    - name: install mariadb package (ubuntu)
      apt: 
        name: 
          - mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: install maria db (centos)
      dnf: 
        name: 
          - mariadb
        state: latest
      when: ansible_distribution == "CentOS"
      
- hosts: File_Server
  become: true
  tasks:
    - name: install samba package
      package: 
        name: 
          - samba
        state: latest

