
---

- hosts: all
  become: true
  tasks:
 - name: install updates (centos)
   dnf:
    update_only: yes
    update_cache: yes
   when: ansible_distribution == "CentOS"
 - name: install updates (centos)
   apt:
     upgrade: dist
     update_cache: yes
   when: ansible_distribution == "Ubuntu"

- hosts: Server_1
  become: true
  tasks:
 - name: install apache and php package ubuntu
   package: 
     name: 
       - apache2
       - libapache2-mod-php
     state: latest
   when: ansible_distribution == "Ubuntu"
 - name: install apache and php package centos
   dnf: 
     name: 
       - httpd
       - php
     state: latest
   when: ansible_distribution == "CentOS"
