- name: install mariadb package (ubuntu)
  tags: db,mariadb,ubuntu
  apt: 
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install maria db (centos)
  tags: db,mariadb,centos
  dnf: 
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"
